var namespaces_dup =
[
    [ "Hints on input files.", "hints.html#autotoc_md17", null ],
    [ "Hints on bonding definitions.", "hints.html#autotoc_md18", null ],
    [ "Hints on external executables", "hints.html#autotoc_md19", null ],
    [ "Common problems", "hints.html#autotoc_md20", null ],
    [ "input", "_tutorial1.html#autotoc_md24", null ],
    [ "start.xyz and end.xyz", "_tutorial1.html#autotoc_md25", null ],
    [ "orca.head", "_tutorial1.html#autotoc_md26", null ],
    [ "orca.min", "_tutorial1.html#autotoc_md27", null ],
    [ "A note on executables for external programs", "_tutorial1.html#autotoc_md28", null ],
    [ "Running the calculation", "_tutorial1.html#autotoc_md29", null ],
    [ "Next steps", "_tutorial1.html#autotoc_md30", null ],
    [ "input", "pathfind.html#autotoc_md31", null ],
    [ "start.xyz and end.xyz", "pathfind.html#autotoc_md32", null ],
    [ "moves.in", "pathfind.html#autotoc_md33", null ],
    [ "Running the calculation", "pathfind.html#autotoc_md34", null ],
    [ "Optimizing structures", "pathfind.html#autotoc_md35", null ],
    [ "Final output and next steps.", "pathfind.html#autotoc_md36", null ],
    [ "chemstr", "namespacechemstr.html", null ],
    [ "constants", "namespaceconstants.html", null ],
    [ "functions", "namespacefunctions.html", null ],
    [ "globaldata", "namespaceglobaldata.html", null ],
    [ "io", "namespaceio.html", null ],
    [ "pathfinder", "namespacepathfinder.html", null ],
    [ "pathopt", "namespacepathopt.html", null ],
    [ "pes", "namespacepes.html", null ],
    [ "rpath", "namespacerpath.html", null ]
];